<a href="https://colab.research.google.com/github/Adityadevhare/ML-learning-journey/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas

#1. Pandas Series
###A series is a one-dimensional labeled array capable of holding any data type . The axis lables are collectively called the index .

In [2]:
##> Crafting a series

import numpy as np
import pandas as pd

lables=['a','b','c']
my_list=[10,20,30]
arr = np.array([10,20,30])
d ={1:10, 2:20, 3:30}

print(f'Created series using list :\n{pd.Series(my_list)} \n')
print(f"Created series using numpy array :\n{pd.Series(arr)} \n")
print(f"Created series using dictionary :\n{pd.Series(d)} \n")

print(f"Labeling the series :\n{pd.Series(data=my_list, index=lables)} \n")
print(f"Labeling the series :\n{pd.Series(my_list, lables)} \n")

##? We can't create an series using 2-D numpy array because the Series itself is 1-D.

Created series using list :
0    10
1    20
2    30
dtype: int64

Created series using numpy array :
0    10
1    20
2    30
dtype: int64

Created series using dictionary :
1    10
2    20
3    30
dtype: int64

Labeling the series :
a    10
b    20
c    30
dtype: int64

Labeling the series :
a    10
b    20
c    30
dtype: int64

#2. Data Frames
###When we combine multiple series it creates a Dataframe .

####i. Creating a dataframe

In [3]:
##> Creating Dataframe using Dictionary.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago'],
    'Salary': [50000, 60000, 70000, 80000]
}

df=pd.DataFrame(data)
print(f'DataFrame using dictionary  :\n {df}\n\n')


##> Creating DataFrams using List.
data_list = [
    ["Alice" , 25 , "New york" , 50000],
    ["Bob" , 30 , "San Francisco" , 60000],
    ["Charlie" , 35 , "Los Angeles" , 70000],
    ["David" , 40 , "Chicago" , 80000]
]

df1=pd.DataFrame(data_list, columns = ["Name" , "Age" , "City" , "Salary"])
print(f'Dataframe using list :\n{df1}\n ')

DataFrame using dictionary  :
       Name  Age           City  Salary
0    Alice   25       New York   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000
3    David   40        Chicago   80000


Dataframe using list :
      Name  Age           City  Salary
0    Alice   25       New york   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000
3    David   40        Chicago   80000

###ii. Selection and Indexing of columns

In [4]:
##> Indexing in Dataframes
# For example let us take the df1 dataframe to undersatnd indexing .

print(f'DataFrame : \n{df1}\n\n')

#> If I want to target the a specific index or columns of the dataframe.Then :
print(f'Targeting the Name column : \n{df1['Name']}\n\n')

#> But if I want to acess 2 or more columns at a same time then  I have to provide the list of list .
print(f'Targeting the Name and Agr of the Dataframe : \n{df1[['Name', 'Age']]}\n')

DataFrame :
      Name  Age           City  Salary
0    Alice   25       New york   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000
3    David   40        Chicago   80000


Targeting the Name column :
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object


Targeting the Name and Agr of the Dataframe :
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

#--------------------------------------------------

# Some practice questions

#1.
###Q1) Create the following DataFrame:
| Name   | Age | City   |
| ------ | --- | ------ |
| Aditya | 19  | Nagpur |
| Rahul  | 20  | Pune   |
| Priya  | 18  | Mumbai |
| Sneha  | 19  | Delhi  |

In [5]:
table_data = {
    'Name':['Aditya' , 'Rahul' , 'Priya' , 'Sneha'],
    'Age':[19,20,18,19],
    'City':['Nagpur' , 'Pune' , 'Mumbai' ,'Delhi']
}

###Q2 Print:
1. Entire DataFrame
2. Only the Name column
3. Only the Age column

In [6]:
##> 1.
print(f'Entire DataFrame : \n{pd.DataFrame(table_data)}\n\n')

##> 2.
print(f'Only the Name column : \n{pd.DataFrame(table_data, columns = ["Name"])}\n\n')

##> 3.
print(f'Only the Age column :\n {pd.DataFrame(table_data, columns = ["Age"])}\n\n')

Entire DataFrame :
     Name  Age    City
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi


Only the Name column :
     Name
0  Aditya
1   Rahul
2   Priya
3   Sneha


Only the Age column :
    Age
0   19
1   20
2   18
3   19

###Q3) Print the following together:

1. Name and City
2. Name and Age

In [7]:
##> 1.
print(f'Name and City :\n{pd.DataFrame(table_data, columns = ["Name" , "City"])}\n\n')

##> 2.
print(f'Name and Age : \n{pd.DataFrame(table_data , columns =["Name" , "Age"])}\n\n')

Name and City :
     Name    City
0  Aditya  Nagpur
1   Rahul    Pune
2   Priya  Mumbai
3   Sneha   Delhi


Name and Age :
     Name  Age
0  Aditya   19
1   Rahul   20
2   Priya   18
3   Sneha   19

#2.
###Use the same DataFrame.

Q1) Change the index to

S1
S2
S3
S4

Then print the DataFrame.

In [8]:
print(f"Changig the index : \n{pd.DataFrame(table_data, index=['S1' , 'S2' , 'S3' , 'S4'])}\n")

Changig the index :
      Name  Age    City
S1  Aditya   19  Nagpur
S2   Rahul   20    Pune
S3   Priya   18  Mumbai
S4   Sneha   19   Delhi

###Q2) Create another DataFrame where the index is

101,
102,
103,
104

In [9]:
change = pd.DataFrame(table_data, index=[101,102,103,104])
print(f"Changing the DataFrame :\n{change}\n")

Changing the DataFrame :
       Name  Age    City
101  Aditya   19  Nagpur
102   Rahul   20    Pune
103   Priya   18  Mumbai
104   Sneha   19   Delhi

###Q3) Print only students having index

101,
103

In [10]:
print(f"Student Data : \n{pd.DataFrame(change, index =[101,103])}\n")

Student Data :
       Name  Age    City
101  Aditya   19  Nagpur
103   Priya   18  Mumbai

#3.
###Create this DataFrame:
| Roll | Name   | Branch | CGPA | Placed |
| ---- | ------ | ------ | ---- | ------ |
| 1    | Aditya | AI     | 8.8  | False  |
| 2    | Rahul  | CSE    | 7.9  | True   |
| 3    | Sneha  | AIDS   | 9.3  | True   |
| 4    | Priya  | IT     | 8.4  | False  |
| 5    | Aman   | AI     | 8.0  | False  |


Q1

Print only

Name
CGPA

In [11]:
##> 1.
mix_data = {
    "Roll":[1,2,3,4,5],
    "Name":['Aditya', 'Rahul','Sneha','Priya','Aman'],
    "Branch":['AI' , 'CSE' , 'AIDS' , 'IT' , 'AI'],
    "CGPA":[8.8 , 7.9 ,9.3 , 8.4 , 8.0],
    "Placed":[False , True , True , False , False]
}
df2=pd.DataFrame(mix_data)
print(f"Name and CGPA : \n{df2[['Name' , 'CGPA']]}\n")

Name and CGPA :
     Name  CGPA
0  Aditya   8.8
1   Rahul   7.9
2   Sneha   9.3
3   Priya   8.4
4    Aman   8.0

### Q2)Print
Roll

Branch

Placed

In [12]:
print(f"Roll , Branch and Placed : \n{df2[['Roll' , 'Branch' , 'Placed']]}\n")

Roll , Branch and Placed :
   Roll Branch  Placed
0     1     AI   False
1     2    CSE    True
2     3   AIDS    True
3     4     IT   False
4     5     AI   False

#-------------------------------------------------

#iii. Creating a new column

In [13]:
new_data={
    'name':['Aditya' , 'Rahul' , 'Priya' , 'Sneha'],
    'age':[19,20,18,19],
    'city':['Nagpur' , 'Pune' , 'Mumbai' ,'Delhi']
}
df3=pd.DataFrame(new_data)


##> In oder to create or add a new column to an existing DataFrame ,
# Here I have already added a new column  to the existing Data Frame that is 'Designation'.

print(f'Original Dataframe : \n{df3}\n')

# Adding a column
##> Here just like indexing we have to provide the name of the column which we want to add and then
#   provide the list of the elements "" , Imp: we have to provide the same no. of elements as in existing dataframe.
df3['Experience']=[2,3,5,6]

##> After adding a column
print(f'After change : \n{df3}\n')

Original Dataframe :
     name  age    city
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi

After change :
     name  age    city  Experience
0  Aditya   19  Nagpur           2
1   Rahul   20    Pune           3
2   Priya   18  Mumbai           5
3   Sneha   19   Delhi           6

#iv. Removing a column

In [14]:
##> Let's take the existing DataFrame 'df3'.
# In order to remove the entire column we have to us the function 'drop'.
df3
# Check if 'Experience' column exists before dropping and reassign the result
# if 'Experience' in df3.columns:
#     df3.drop('Experience', axis=1)
# print(f"After droping the Experience column : \n{df3}\n")

df3.drop('Experience', axis=1)

     name  age    city
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi

In [15]:
##? But if we check the df3 dataframe again we see that :
print(f"dataFrame : \n{df3}\n\n")

##> The experience column is not being removed .
#   This is beacuse the we haven't provide the inplace parameter to the drop function.
#   Due to which a temporary sanpshot of the operation is being displayed .
#   TO actully delete the column we have to provide the inplace parameter.

print(f"{df3.drop('Experience', axis=1 , inplace=True)}")

# Here the output shows none , but if I execute the df3 in another cell we'll see.

dataFrame :
     name  age    city  Experience
0  Aditya   19  Nagpur           2
1   Rahul   20    Pune           3
2   Priya   18  Mumbai           5
3   Sneha   19   Delhi           6


None

In [16]:
df3
#Now here you can see that the experience column is now deleted Permanently from dataframe.

     name  age    city
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi

In [17]:
##> Now if we want to delete the 2 or columns the , we have to provide the list od column names.

print(f"Deleting multiple columns : {df3.drop(['age' , 'city'] , axis=1 , inplace=True)}")

Deleting multiple columns : None

In [18]:
df3

     name
0  Aditya
1   Rahul
2   Priya
3   Sneha

#v. Selecting Column

In [19]:
row_data={
    'name':['Aditya' , 'Rahul' , 'Priya' , 'Sneha'],
    'age':[19,20,18,19],
    'city':['Nagpur' , 'Pune' , 'Mumbai' ,'Delhi'],
    'designation':['AI' , 'CSE' , 'AIDS' , 'IT'],
    'experience':[2,3,5,6]
}
df4=pd.DataFrame(row_data)
print(f"DataFrame :\n{df4}\n\n")

##> For understanding how to acess the rows I've made a new DataFrame.
# In order to target the rows of the DataFrame we hae to use the function loc.

print(f"Acessing the first row :\n{df4.loc[0]}\n")

##> we can alo target multiple rows at once by sepearting the row number by commas.

print(f"Acessing multipe rows : \n{df4.loc[[1,2]]}")


##> There is one more function 'iloc()' that targets the rows by there index value .

DataFrame :
     name  age    city designation  experience
0  Aditya   19  Nagpur          AI           2
1   Rahul   20    Pune         CSE           3
2   Priya   18  Mumbai        AIDS           5
3   Sneha   19   Delhi          IT           6


Acessing the first row :
name           Aditya
age                19
city           Nagpur
designation        AI
experience          2
Name: 0, dtype: object

Acessing multipe rows :
    name  age    city designation  experience
1  Rahul   20    Pune         CSE           3
2  Priya   18  Mumbai        AIDS           5

#vi. Selecting Subsets of Rows and Columns

In [20]:
##> I order to to tarrget a particular row and column uh we have to provide Row number and the column name.
df4.loc[[0,1]][['age','city']]

   age    city
0   19  Nagpur
1   20    Pune

#vii. Conditional Selection.

In [21]:
df4

     name  age    city designation  experience
0  Aditya   19  Nagpur          AI           2
1   Rahul   20    Pune         CSE           3
2   Priya   18  Mumbai        AIDS           5
3   Sneha   19   Delhi          IT           6

In [22]:
##> If I only want to see the persons name whose age is greater than 18.
df4[df4['age']>19]

    name  age  city designation  experience
1  Rahul   20  Pune         CSE           3

In [23]:
# Now what if
##> I want to select the person whose age is grater than 18 and belong form Nagpur.
##>> Here we'll use 'and (&)' and 'or (|)' operations.
df4[(df4['age'] > 18) & (df4['city'] == 'Nagpur')]

     name  age    city designation  experience
0  Aditya   19  Nagpur          AI           2

#Missing Data

#i. Finding Missing data

In [24]:
import numpy as np
import pandas as pd

missing_data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}

df5=pd.DataFrame(missing_data)
df5

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [25]:
##> TO check wheather the value is persent in the dataframe or not we use the function 'isna()'

df5.isna()

##> It returns the value either True or Flase .
# If the value is persent then -> False
# If the value is not present then -> True

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [26]:
##> And If you wnat the cout of missing vaules .
df5.isna().sum()

#> This is for the rows.

A    1
B    1
C    2
D    3
dtype: int64

In [27]:
##> But what if I want it for the coulmn , like I wnat to check that wheather there is a missing value in my any of the columns of the DataFrame .

df5.isna().any()

#> by uing any() function we we can find out that wheather there exists an empty place in the columns or not .
# If there exists -> True
# If not -> False

A    True
B    True
C    True
D    True
dtype: bool

# ii. Removing Missing Values

In [28]:
df5

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [29]:
##> Using dropna()

# By using the dropna() function , the output shows a sanpshot of the removed Nan rows .
#> As in my case all the rows will be diappered as every row contanin a missing value.


df5.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [30]:
##> Passing the 'threshold' parameter to the "dropna()"
#? What does the thres do ?
# > in thershold we usually pass a number(integer) and it sreachs that
# perticular row with a non-nan value .

df5.dropna(thresh=3)


# > If we are providing the thresh more thaan the number of the columns than the
# output will be an empty DataFrame .

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

#iii. Filling missing data

In [31]:
df5

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [32]:
##> fillna() function
#> By using fillna() function we can fill a value to all of the missing palce .

## All the change that we are doing are not Temporary because I'm not passing the inplace parameter to True.

df5.fillna(0)

## now as you can see that all the missing values are now being replaced by 0.
###> Not on ly zero we can pass any value , string , integer ,float any datatype but properly.
#    Like strings must be passed in quotes only .

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [33]:
###? Now what if we want to replace the value of column A to 0 and other columns with any other values ?
##> For that we have to pass the value parameter to the fillna().
#> But before that we need to make a Dictionary of values according to the rows.
#> Or we can pass the dictionary directly without creating one externally.

df5.fillna(value={'A':10 , 'B':55 , 'C':56.3 , 'D':'x'})

      A     B     C    D
0   1.0  55.0   1.0  1.0
1   2.0   2.0   2.0    x
2  10.0   3.0   3.0    x
3   4.0   4.0  56.3    x
4   5.0   5.0  56.3  5.0

In [34]:
##> But always filling an random value is not a soultion  .
# SO we use statstical operations like mean .
df5.fillna(df5.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [35]:
df5.fillna(df5.std())

          A         B    C         D
0  1.000000  1.290994  1.0  1.000000
1  2.000000  2.000000  2.0  2.828427
2  1.825742  3.000000  3.0  2.828427
3  4.000000  4.000000  1.0  2.828427
4  5.000000  5.000000  1.0  5.000000

# Merging , Joining and Concatination

#i. Merging 2 DataFrames

In [36]:
sample1=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['Jhon', 'Anna' , 'Peter' , 'Linda' , 'Bob'],
    'department':['HR' , 'IT' , 'Finance' , 'IT' , 'HR']
})

sample2=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[60000 , 80000 , 65000 , 70000 , 90000],
    'bouns':[5000 , 10000 , 7000 , 8000 , 12000]
})

In [37]:
sample1

   employee_id   name department
0            1   Jhon         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [38]:
sample2

   employee_id  salary  bouns
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [39]:
##> In order to merge two dataframes we must have comman column in both of the DataFrame .
pd.merge(sample1,sample2)

#> Only employee_id is a comman column in both of the DaatFrame.
#> As you can see that only 3 columns appered because there are 3 comman employee_ids in bothe the DataFrames.

   employee_id   name department  salary  bouns
0            1   Jhon         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [40]:
#> Another parameter .
pd.merge(sample1 , sample2 , on='employee_id')

   employee_id   name department  salary  bouns
0            1   Jhon         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [41]:
##> there is one more parameter , and that is 'how' .
#> We can pass 4 string to "how" i.e., 'inner' , 'outer' , 'right' & 'left' .

#> Inner means to merge on the basis of comman values in the comman column.
#> Outter means to merge on the basis of non-comman values of the comman column.

pd.merge(sample1,sample2,on='employee_id',how='inner')

   employee_id   name department  salary  bouns
0            1   Jhon         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [42]:
pd.merge(sample1,sample2,on='employee_id',how='outer')

##? As we can see that all the cells are merged now and the column value were missing are filled with Nan( Not a number ).

   employee_id   name department   salary    bouns
0            1   Jhon         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [43]:
pd.merge(sample1,sample2,on='employee_id',how='left')

#> This means that we have to merge the Dataframe On the basis of the first dataframe.

   employee_id   name department   salary    bouns
0            1   Jhon         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [44]:
pd.merge(sample1 , sample2 , on='employee_id' , how = 'right')

#> And this means that we have to merge the dataframes on the basis of second dataframe

   employee_id   name department  salary  bouns
0            1   Jhon         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#ii. Concatenation of 2 dataframes

In [45]:
##> Lets take 2 more sample dataframes.
c1=pd.DataFrame({
    'A':['A0' , 'A1' , 'A2'],
    'B':['B0' , 'B1' , 'B2'],
    'C':['C0' , 'C1' , 'C2']
})

c2=pd.DataFrame({
    'A':['A3' , 'A4' , 'A5'],
    'B':['B3' , 'B4' , 'B5'],
    'C':['C3' , 'C4' , 'C5']
})

In [46]:
c1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [47]:
c2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [48]:
pd.concat([c1,c2])

#> We can concaa]t on the basis of either columns or rows .
#> Here it's with respect ot columns , because I've not passed the 'axis' parameter and by default it's 0 (means columns ).

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [49]:
#> but for rows we can pass the "axis" parameter to 1 (means rows).

pd.concat([c1,c2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#iii. Joining 2 DataFrames

In [50]:
##> Again we have to take two sample DataFrames.
j1=pd.DataFrame({
    'name':['Alice' , 'Bob' , 'Charlie'],
} , index=[i for i in range(1,4,1)])

j2=pd.DataFrame({
    'score':[85,90,75],
}, index=[i for i in range(2,5,1)])

In [51]:
j1

      name
1    Alice
2      Bob
3  Charlie

In [52]:
j2

   score
2     85
3     90
4     75

In [53]:
##> we can join two Pandas Series by us by the keyword ".join()".
#> Here the series before "." will accqire the first position on the DataFrame nd the series in the paranthsis will accquire the second place .

j1.join(j2)

##> Here we can see that the there is NaN in the first row it's because the join keyword concats the series serial wise and as there is no value to be placed for Alice there exists an NaN.

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [54]:
##> The above cell represents the inner joining .

#> The outer one look like .

j1.join(j2,how='outer')

#> It will join the entire Series.

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

#Group by Aggergation

### i. Group by

In [59]:
##>

data ={
    'Category':['A','B','A','B','A','B','A','B'],
    'Store':['S1','S2','S1','S1','S2','S1','S2','S2'],
    'Sales':[100,200,150,250,300,350,400,450],
    'Quantity':[5,10,15,20,25,30,35,40],
    'Date':pd.date_range('2026-01-01',periods=8)
}

df6=pd.DataFrame(data)
df6

  Category Store  Sales  Quantity       Date
0        A    S1    100         5 2026-01-01
1        B    S2    200        10 2026-01-02
2        A    S1    150        15 2026-01-03
3        B    S1    250        20 2026-01-04
4        A    S2    300        25 2026-01-05
5        B    S1    350        30 2026-01-06
6        A    S2    400        35 2026-01-07
7        B    S2    450        40 2026-01-08

In [64]:
#? Group by category and claculate the sum of sales .
Group =df6.groupby('Category')
print(Group)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7cf6306619d0>

In [69]:

#> As swe can see that the groupby() function has created an object .
#> Which we can't access directly , so we have to use a loop over this object .
for i , v in Group:
  print(i)
  print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100         5 2026-01-01
2        A    S1    150        15 2026-01-03
4        A    S2    300        25 2026-01-05
6        A    S2    400        35 2026-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S2    200        10 2026-01-02
3        B    S1    250        20 2026-01-04
5        B    S1    350        30 2026-01-06
7        B    S2    450        40 2026-01-08