<a href="https://colab.research.google.com/github/Adityadevhare/ML-learning-journey/blob/main/Pandas_Small_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('/content/sample_data/anime.csv')

In [13]:
# .head() is used to read the first 5 rows of the DataFrame .

df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

#Questions

## Q1) Make a new column for episode count .

In [31]:
##> Now we'll first do the feture extraction .
#> But before that we should check the details in row :

print(df.loc[0]['Title'])
print(df.loc[1]['Title'])
print(df.loc[2]['Title'])
print(df.loc[3]['Title'])
print(df.loc[4]['Title'])

##> Ok , I won't be looking Throughout the entire data frame So now I'll extract the episode count.

def extract_episode(my_dataframe):
    check = False
    data = ""
    for i in my_dataframe:
        # 1.string comparison: compare char 'i' instead of boolean 'check'
        if i == ')':
            check = False
            return int(data)  # Convert to integer (or return data.strip() if you want string)

        if check == True:
            # 2. Skip the 'eps' text so you only collect the numbers
            if i.isdigit():
                data += i

        if i == '(':
            check = True

    return data

##> Here I have already removed the eps , because I have to apply Aggregate functions on this dataframe .
df['Episode Count'] = df['Title'].apply(extract_episode)
df['Episode Count']

Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview
Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members
Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members
Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members
Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview

0      64
1      24
2      13
3      51
4      10
5      51
6       1
7     148
8      13
9      13
10      2
11    110
12     13
13     13
14     12
15    201
16      1
17     22
18     24
19     25
20      1
21      1
22      7
23     14
24     74
25      1
26      1
27     12
28      1
29     24
30     23
31     12
32     26
33     13
34     16
35     11
36      1
37     11
38     10
39      1
40     26
41     12
42     75
43     26
44     26
45     24
46     10
47     12
48     12
49      4
Name: Episode Count, dtype: int64

In [32]:
##> Now our dataframe look like this .

df

#> Another way of removing eps is like

# df['Episode Count'].str.replace('(eps)','').astype(int)
# df['Episode Count'].astype(int)

,Rank,Title,Score,Episode Count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4

## Q2) Make a new column for time stamp and Months .

In [30]:
# > Now I have to again extract the data for Time stamp .

df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [35]:
def extract_timestamp(my_dataframe):
    check = False
    data = ""
    for i in my_dataframe:
        if check == True and i == ",":
            return data
        if check == True:
            data += i
        if i == ')':
            check = True
    return data

#> Another approch :

# def extract_timestamp(my_dataframe):
#   check = False
#   data = ""
#   for i in range(len(my_dataframe)):
#     if my_dataframe[i] == ')':
#       for j in range(i+1, i+20):
#         data += my_dataframe[j]
#       return data
#       break

#   return data


df['Time Stamp'] = df['Title'].apply(extract_timestamp)
df['Time Stamp']

0        Apr 2009 - Jul 20103
1        Apr 2011 - Sep 20112
2      Oct 2022 - Dec 2022474
3      Apr 2015 - Mar 2016605
4        Apr 2019 - Jul 20192
5      Apr 2011 - Mar 2012534
6      Jan 2021 - Jan 2021137
7        Oct 2011 - Sep 20142
8      Apr 2022 - Jun 2022851
9      Oct 2012 - Mar 2013313
10     Mar 2023 - May 2023472
11     Jan 1988 - Mar 1997309
12    Jul 2023 - Aug 2023 178
13     Apr 2021 - Jun 2021443
14     Jan 2017 - Mar 2017302
15       Apr 2006 - Mar 20101
16       Sep 2016 - Sep 20162
17     Oct 2017 - Mar 2018388
18       Oct 2008 - Mar 20091
19       Apr 2008 - Sep 20081
20     Jul 2013 - Jul 2013232
21     Sep 2020 - Sep 2020564
22     Aug 2017 - Aug 2017385
23     Jul 2018 - Oct 2018189
24       Apr 2004 - Sep 20051
25       Aug 2016 - Aug 20162
26     Dec 2022 - Dec 2022205
27     Oct 2022 - Dec 2022464
28      Dec 2022 - Dec 202227
29     Jan 2023 - Jun 2023495
30    Jul 2023 - Aug 2023 556
31     Jan 2018 - Mar 2018203
32      Apr 2020 - Oct 202193
33       Jan 2019 - Apr 20191
34       Dec 2020 - Mar 20211
35       Dec 2021 - Feb 20221
36     Jan 2017 - Jan 2017445
37     Apr 2023 - Jun 2023645
38       Oct 2016 - Dec 20161
39       Jul 2001 - Jul 20011
40     Jul 2013 - Dec 2013653
41       Jan 2022 - Apr 20221
42     Oct 2000 - Mar 2002558
43       Apr 1998 - Apr 19991
44      Apr 2022 - Oct 202255
45       Jul 2019 - Dec 20191
46     Oct 2014 - Dec 2014257
47     Jan 2017 - Mar 2017182
48     Oct 2022 - Dec 2022600
49     Feb 1999 - Sep 1999271
Name: Time Stamp, dtype: object

In [36]:
df

,Rank,Title,Score,Episode Count,Time Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 20103
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 20112
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022474
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016605
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 20192
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012534
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021137
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 20142
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022851
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013313
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023472
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997309
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023 178
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021443
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017302
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 20101
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 20162
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018388
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 20091
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 20081
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013232
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020564
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017385
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018189
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 20051
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 20162
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022205
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022464
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 202227
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023495
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023 556
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018203
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 202193
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 20191
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 20211
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 20221
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017445
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023645
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 20161
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 20011
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013653
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 20221
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002558
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 19991
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 202255
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 20191
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014257
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017182
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022600
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999271

In [40]:
#> Now I want to calculate the total number of months (I mean time period).


from datetime import datetime
from dateutil.relativedelta import relativedelta
import re


def calculate_total_months(period):
    try:
        # Split into start and end parts
        start_str, end_str = period.split(" - ")

        # Clean end_str so it only keeps 'MMM YYYY' (3 letters + space + 4 digits)
        end_str = re.search(r"[A-Za-z]{3}\s+\d{4}", end_str).group(0)
        start_str = start_str.strip()

        start_date = datetime.strptime(start_str, "%b %Y")
        end_date = datetime.strptime(end_str, "%b %Y")

        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include starting month
    except Exception as e:
        return None


df["Months"] = df["Time Stamp"].apply(calculate_total_months)
df["Months"]

0      16
1       6
2       3
3      12
4       4
5      12
6       1
7      36
8       3
9       6
10      3
11    111
12      2
13      3
14      3
15     48
16      1
17      6
18      6
19      6
20      1
21      1
22      1
23      4
24     18
25      1
26      1
27      3
28      1
29      6
30      2
31      3
32     19
33      4
34      4
35      3
36      1
37      3
38      3
39      1
40      6
41      4
42     18
43     13
44      7
45      6
46      3
47      3
48      3
49      8
Name: Months, dtype: int64

In [41]:
df

,Rank,Title,Score,Episode Count,Time Stamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 20103,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 20112,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022474,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016605,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 20192,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012534,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021137,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 20142,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022851,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013313,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023472,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997309,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023 178,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021443,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017302,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 20101,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 20162,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018388,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 20091,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 20081,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013232,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020564,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017385,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018189,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 20051,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 20162,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022205,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022464,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 202227,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023495,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023 556,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018203,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 202193,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 20191,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 20211,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 20221,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017445,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023645,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 20161,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 20011,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013653,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 20221,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002558,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 19991,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 202255,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 20191,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014257,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017182,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022600,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999271,8

## Q3) Which anime has the highest score.

In [43]:
##> MAximun score can be found like ,

df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,Episode Count,Time Stamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 20103,16

##Q4) Give top five highest scoring anime .

## Q5) Which anime has the highest episode count

##Q6) Anime with top five episode count

## Q7) Which is the longest running anime.