<a href="https://colab.research.google.com/github/Adityadevhare/ML-learning-journey/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas

#1. Pandas Series
###A series is a one-dimensional labeled array capable of holding any data type . The axis lables are collectively called the index .

In [1]:
##> Crafting a series

import numpy as np
import pandas as pd

lables=['a','b','c']
my_list=[10,20,30]
arr = np.array([10,20,30])
d ={1:10, 2:20, 3:30}

print(f'Created series using list :\n{pd.Series(my_list)} \n')
print(f"Created series using numpy array :\n{pd.Series(arr)} \n")
print(f"Created series using dictionary :\n{pd.Series(d)} \n")

print(f"Labeling the series :\n{pd.Series(data=my_list, index=lables)} \n")
print(f"Labeling the series :\n{pd.Series(my_list, lables)} \n")

##? We can't create an series using 2-D numpy array because the Series itself is 1-D.

Created series using list :
0    10
1    20
2    30
dtype: int64

Created series using numpy array :
0    10
1    20
2    30
dtype: int64

Created series using dictionary :
1    10
2    20
3    30
dtype: int64

Labeling the series :
a    10
b    20
c    30
dtype: int64

Labeling the series :
a    10
b    20
c    30
dtype: int64

#2. Data Frames
###When we combine multiple series it creates a Dataframe .

####i. Creating a dataframe

In [2]:
##> Creating Dataframe using Dictionary.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago'],
    'Salary': [50000, 60000, 70000, 80000]
}

df=pd.DataFrame(data)
print(f'DataFrame using dictionary  :\n {df}\n\n')


##> Creating DataFrams using List.
data_list = [
    ["Alice" , 25 , "New york" , 50000],
    ["Bob" , 30 , "San Francisco" , 60000],
    ["Charlie" , 35 , "Los Angeles" , 70000],
    ["David" , 40 , "Chicago" , 80000]
]

df1=pd.DataFrame(data_list, columns = ["Name" , "Age" , "City" , "Salary"])
print(f'Dataframe using list :\n{df1}\n ')

DataFrame using dictionary  :
       Name  Age           City  Salary
0    Alice   25       New York   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000
3    David   40        Chicago   80000


Dataframe using list :
      Name  Age           City  Salary
0    Alice   25       New york   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000
3    David   40        Chicago   80000

###ii. Selection and Indexing of columns

In [3]:
##> Indexing in Dataframes
# For example let us take the df1 dataframe to undersatnd indexing .

print(f'DataFrame : \n{df1}\n\n')

#> If I want to target the a specific index or columns of the dataframe.Then :
print(f'Targeting the Name column : \n{df1['Name']}\n\n')

#> But if I want to acess 2 or more columns at a same time then  I have to provide the list of list .
print(f'Targeting the Name and Agr of the Dataframe : \n{df1[['Name', 'Age']]}\n')

DataFrame :
      Name  Age           City  Salary
0    Alice   25       New york   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000
3    David   40        Chicago   80000


Targeting the Name column :
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object


Targeting the Name and Agr of the Dataframe :
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

#--------------------------------------------------

# Some practice questions

#1.
###Q1) Create the following DataFrame:
| Name   | Age | City   |
| ------ | --- | ------ |
| Aditya | 19  | Nagpur |
| Rahul  | 20  | Pune   |
| Priya  | 18  | Mumbai |
| Sneha  | 19  | Delhi  |

In [ ]:
table_data = {
    'Name':['Aditya' , 'Rahul' , 'Priya' , 'Sneha'],
    'Age':[19,20,18,19],
    'City':['Nagpur' , 'Pune' , 'Mumbai' ,'Delhi']
}

###Q2 Print:
1. Entire DataFrame
2. Only the Name column
3. Only the Age column

In [ ]:
##> 1.
print(f'Entire DataFrame : \n{pd.DataFrame(table_data)}\n\n')

##> 2.
print(f'Only the Name column : \n{pd.DataFrame(table_data, columns = ["Name"])}\n\n')

##> 3.
print(f'Only the Age column :\n {pd.DataFrame(table_data, columns = ["Age"])}\n\n')

Entire DataFrame :
     Name  Age    City
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi


Only the Name column :
     Name
0  Aditya
1   Rahul
2   Priya
3   Sneha


Only the Age column :
    Age
0   19
1   20
2   18
3   19

###Q3) Print the following together:

1. Name and City
2. Name and Age

In [ ]:
##> 1.
print(f'Name and City :\n{pd.DataFrame(table_data, columns = ["Name" , "City"])}\n\n')

##> 2.
print(f'Name and Age : \n{pd.DataFrame(table_data , columns =["Name" , "Age"])}\n\n')

Name and City :
     Name    City
0  Aditya  Nagpur
1   Rahul    Pune
2   Priya  Mumbai
3   Sneha   Delhi


Name and Age :
     Name  Age
0  Aditya   19
1   Rahul   20
2   Priya   18
3   Sneha   19

#2.
###Use the same DataFrame.

Q1) Change the index to

S1
S2
S3
S4

Then print the DataFrame.

In [ ]:
print(f"Changig the index : \n{pd.DataFrame(table_data, index=['S1' , 'S2' , 'S3' , 'S4'])}\n")

Changig the index :
      Name  Age    City
S1  Aditya   19  Nagpur
S2   Rahul   20    Pune
S3   Priya   18  Mumbai
S4   Sneha   19   Delhi

###Q2) Create another DataFrame where the index is

101,
102,
103,
104

In [ ]:
change = pd.DataFrame(table_data, index=[101,102,103,104])
print(f"Changing the DataFrame :\n{change}\n")

Changing the DataFrame :
       Name  Age    City
101  Aditya   19  Nagpur
102   Rahul   20    Pune
103   Priya   18  Mumbai
104   Sneha   19   Delhi

###Q3) Print only students having index

101,
103

In [ ]:
print(f"Student Data : \n{pd.DataFrame(change, index =[101,103])}\n")

Student Data :
       Name  Age    City
101  Aditya   19  Nagpur
103   Priya   18  Mumbai

#3.
###Create this DataFrame:
| Roll | Name   | Branch | CGPA | Placed |
| ---- | ------ | ------ | ---- | ------ |
| 1    | Aditya | AI     | 8.8  | False  |
| 2    | Rahul  | CSE    | 7.9  | True   |
| 3    | Sneha  | AIDS   | 9.3  | True   |
| 4    | Priya  | IT     | 8.4  | False  |
| 5    | Aman   | AI     | 8.0  | False  |


Q1

Print only

Name
CGPA

In [ ]:
##> 1.
mix_data = {
    "Roll":[1,2,3,4,5],
    "Name":['Aditya', 'Rahul','Sneha','Priya','Aman'],
    "Branch":['AI' , 'CSE' , 'AIDS' , 'IT' , 'AI'],
    "CGPA":[8.8 , 7.9 ,9.3 , 8.4 , 8.0],
    "Placed":[False , True , True , False , False]
}
df2=pd.DataFrame(mix_data)
print(f"Name and CGPA : \n{df2[['Name' , 'CGPA']]}\n")

Name and CGPA :
     Name  CGPA
0  Aditya   8.8
1   Rahul   7.9
2   Sneha   9.3
3   Priya   8.4
4    Aman   8.0

### Q2)Print
Roll

Branch

Placed

In [ ]:
print(f"Roll , Branch and Placed : \n{df2[['Roll' , 'Branch' , 'Placed']]}\n")

Roll , Branch and Placed :
   Roll Branch  Placed
0     1     AI   False
1     2    CSE    True
2     3   AIDS    True
3     4     IT   False
4     5     AI   False

#-------------------------------------------------

#iii. Creating a new column

In [18]:
new_data={
    'name':['Aditya' , 'Rahul' , 'Priya' , 'Sneha'],
    'age':[19,20,18,19],
    'city':['Nagpur' , 'Pune' , 'Mumbai' ,'Delhi']
}
df3=pd.DataFrame(new_data)


##> In oder to create or add a new column to an existing DataFrame ,
# Here I have already added a new column  to the existing Data Frame that is 'Designation'.

print(f'Original Dataframe : \n{df3}\n')

# Adding a column
##> Here just like indexing we have to provide the name of the column which we want to add and then
#   provide the list of the elements "" , Imp: we have to provide the same no. of elements as in existing dataframe.
df3['Experience']=[2,3,5,6]

##> After adding a column
print(f'After change : \n{df3}\n')

Original Dataframe :
     name  age    city
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi

After change :
     name  age    city  Experience
0  Aditya   19  Nagpur           2
1   Rahul   20    Pune           3
2   Priya   18  Mumbai           5
3   Sneha   19   Delhi           6

#iv. Removing a column

In [20]:
##> Let's take the existing DataFrame 'df3'.
# In order to remove the entire column we have to us the function 'drop'.
df3
# Check if 'Experience' column exists before dropping and reassign the result
# if 'Experience' in df3.columns:
#     df3.drop('Experience', axis=1)
# print(f"After droping the Experience column : \n{df3}\n")

df3.drop('Experience', axis=1)

     name  age    city
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi

In [22]:
##? But if we check the df3 dataframe again we see that :
print(f"dataFrame : \n{df3}\n\n")

##> The experience column is not being removed .
#   This is beacuse the we haven't provide the inplace parameter to the drop function.
#   Due to which a temporary sanpshot of the operation is being displayed .
#   TO actully delete the column we have to provide the inplace parameter.

print(f"{df3.drop('Experience', axis=1 , inplace=True)}")

# Here the output shows none , but if I execute the df3 in another cell we'll see.

dataFrame :
     name  age    city  Experience
0  Aditya   19  Nagpur           2
1   Rahul   20    Pune           3
2   Priya   18  Mumbai           5
3   Sneha   19   Delhi           6


None

In [23]:
df3
#Now here you can see that the experience column is now deleted Permanently from dataframe.

     name  age    city
0  Aditya   19  Nagpur
1   Rahul   20    Pune
2   Priya   18  Mumbai
3   Sneha   19   Delhi

In [24]:
##> Now if we want to delete the 2 or columns the , we have to provide the list od column names.

print(f"Deleting multiple columns : {df3.drop(['age' , 'city'] , axis=1 , inplace=True)}")

Deleting multiple columns : None

In [25]:
df3

     name
0  Aditya
1   Rahul
2   Priya
3   Sneha

#v. Selecting Column

In [33]:
row_data={
    'name':['Aditya' , 'Rahul' , 'Priya' , 'Sneha'],
    'age':[19,20,18,19],
    'city':['Nagpur' , 'Pune' , 'Mumbai' ,'Delhi'],
    'designation':['AI' , 'CSE' , 'AIDS' , 'IT'],
    'experience':[2,3,5,6]
}
df4=pd.DataFrame(row_data)
print(f"DataFrame :\n{df4}\n\n")

##> For understanding how to acess the rows I've made a new DataFrame.
# In order to target the rows of the DataFrame we hae to use the function loc.

print(f"Acessing the first row :\n{df4.loc[0]}\n")

##> we can alo target multiple rows at once by sepearting the row number by commas.

print(f"Acessing multipe rows : \n{df4.loc[[1,2]]}")


##> There is one more function 'iloc()' that targets the rows by there index value .

DataFrame :
     name  age    city designation  experience
0  Aditya   19  Nagpur          AI           2
1   Rahul   20    Pune         CSE           3
2   Priya   18  Mumbai        AIDS           5
3   Sneha   19   Delhi          IT           6


Acessing the first row :
name           Aditya
age                19
city           Nagpur
designation        AI
experience          2
Name: 0, dtype: object

Acessing multipe rows :
    name  age    city designation  experience
1  Rahul   20    Pune         CSE           3
2  Priya   18  Mumbai        AIDS           5

#vi. Selecting Subsets of Rows and Columns

In [34]:
##> I order to to tarrget a particular row and column uh we have to provide Row number and the column name.
df4.loc[[0,1]][['age','city']]

   age    city
0   19  Nagpur
1   20    Pune

#vii. Conditional Selection.

In [35]:
df4

     name  age    city designation  experience
0  Aditya   19  Nagpur          AI           2
1   Rahul   20    Pune         CSE           3
2   Priya   18  Mumbai        AIDS           5
3   Sneha   19   Delhi          IT           6

In [38]:
##> If I only want to see the persons name whose age is greater than 18.
df4[df4['age']>19]

    name  age  city designation  experience
1  Rahul   20  Pune         CSE           3

In [40]:
# Now what if
##> I want to select the person whose age is grater than 18 and belong form Nagpur.
##>> Here we'll use 'and (&)' and 'or (|)' operations.
df4[(df4['age'] > 18) & (df4['city'] == 'Nagpur')]

     name  age    city designation  experience
0  Aditya   19  Nagpur          AI           2